run:
  timeout: 20m
  go: "1.22"
  modules-download-mode: vendor

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - /submodules/ # Excluding submodules folders as these are externally generated

linters:
  disable-all: true
  enable:
    - asasalint # check for pass []any as any in variadic func(...any)
    - asciicheck # ensure code does not contain non-ASCII identifiers
    - bidichk # checks for dangerous unicode character sequences
    - decorder # check declaration order and count of types, constants, variables and functions.
    - durationcheck # check for common mistakes when working with time.Duration
    - dupword # check for duplicated words in comments
    - errcheck # checking for unchecked errors
    - gocritic # linter for Go source code that specializes in simplifying code
    - gofmt # checks whether code was gofmt-ed
    - gofumpt # checks whether code was gofumpt-ed, a stricter gofmt
    - goimports # check import statements are formatted according to the 'goimport' command
    - gosimple # linter for Go source code that specializes in simplifying code.
    - govet # reports suspicious constructs. It is roughly the same as 'go vet' (replaced vet and vetshadow)
    - ineffassign # detects when assignments to existing variables are not used
    - misspell # finds commonly misspelled English words.
    - nilerr # Finds code that returns nil after it checks that the error is not nil.
    - prealloc # finds slice declarations that could potentially be pre-allocated.
    - predeclared # find code that shadows one of Go's predeclared identifiers.
    - reassign # checks that package variables are not reassigned.
    - tenv #detects using os.Setenv instead of t.Setenv since Go1.17.
    - tagalign #  checks struct tags that do not align with the specified column in struct definitions.
    - staticcheck # checks rules from staticcheck. It's not the same thing as the staticcheck binary.
    - unused # checks Go code for unused constants, variables, functions and types.
    - unconvert # checks for unnecessary type conversions.
    - unparam # reports unused function parameters.
    - wastedassign # finds wasted assignment statements
    - whitespace # checks for unnecessary newlines at the start and end of functions, if, for, etc. (

linters-settings:
  errcheck:
    exclude-functions:
  misspell:
    ignore-words:
  nakedret:
    max-func-lines: 30
  predeclared:
    ignore: new,min,max,len # should we use newer, minimum, and maximum instead?